### ISSUE TITLE
Add `toLines()` trait

### ISSUE THREAD

**Issue by sormuras** [forax/record-util#2]
Interested in adding a trait for a multi-line `toString()` variant that indents each nested component on a best-effort basis?

Something similar to https://sormuras.github.io/blog/2020-05-06-records-to-text-block.html

**Comment by forax** [comment]
Hi Christian,
yes, maybe with a syntax closer to JSON, with the record name in comment ?

**Comment by sormuras** [comment]
Ho! 🤓 

Sure, will create a PR later. Perhaps one with taking arguments for the style and indentation strings...

`.toLines(Style.JSON, "  ") {...}`

Return type?
- `String` (with configurable new line character, of course)
- `List<String>`
- `Stream<String>`

**Comment by forax** [comment]
I wonder if a String is not enough.
I'm not a fan of toLines(JSON), i would prefer two methods, one toJSON() and one toHumanReadableJSONLike() which uses JSON + comment + several lines as format

**Comment by forax** [comment]
see https://github.com/forax/record-util/blob/master/src/main/java/com/github/forax/recordutil/JSONTrait.java for a skeleton implementation (no recursion, etc)

**Comment by forax** [comment]
I've implemented a version that generates a human readable JSON
see https://github.com/forax/record-util/commit/a5c8fe69961be62ec9eb4fd5b42438d5cbd166ee
