### ISSUE TITLE
Fix GH CI workflow 

### ISSUE THREAD

**Issue by sormuras** [forax/record-util#3]
And uploade module to GH Release?

Happy to create a PR.

**Comment by forax** [comment]
Github release or github package ?
(i've never used the later)

**Comment by sormuras** [comment]
Both.

Rémi Forax <notifications@github.com> schrieb am Mo., 22. Feb. 2021, 18:32:

**Comment by forax** [comment]
ok good :)

**Comment by sormuras** [comment]
GH Packages still "suffer" from not being accesible unauthenicated.

And due to its permanent nature (you can't delete packages once deployed), one shouldn't upload a version on each commit. Let's create a dedicated `release` workflow later.

**Comment by sormuras** [comment]
https://github.com/forax/record-util/releases/tag/SNAPSHOT is here, no modular JAR attached. Please reopen this issue.

**Comment by forax** [comment]
re-open the issue !

**Comment by sormuras** [comment]
![image](https://user-images.githubusercontent.com/2319838/108759944-5261ba00-754d-11eb-9255-84ddd4dab3b7.png)

Should be consumable by [Bach](https://github.com/sormuras/bach) out-of-the-box... 😉
